### ISSUE TITLE
Installation for cpu only fails

### ISSUE THREAD

**Issue by VathsalaAchar** [fastai/fastai_pytorch#46]
Is it necessary to have the `cupy` library in the requirements? I cannot install this on my local machine, and get the error:
`Exception: Your CUDA environment is invalid. Please check above error log.`

**Comment by stas00** [comment]
Hi @VathsalaAchar, it's difficult to help answer your question if you don't tell us specifically what you did when you got the error. i.e. how were you installing, etc. Imagine yourself in my shoes when I have no idea what you did and you'd like me to help you, and you will know what information needs to be shared.

Incidentally though we are discussing whether `cupy` should be in the requirements. So stay tuned.

**Comment by TheShadow29** [comment]
@VathsalaAchar That seems to be an error with CUDA installation. I am not sure how you have configured CUDA in your device. According to https://docs-cupy.chainer.org/en/latest/install.html#install-cupy you should do pip install according to your cuda version.

**Comment by stas00** [comment]
Ah, thank you for providing the details. I'm in the process of writing documentation on the various ways to install things. For now do:

    conda install pytorch-nightly -c pytorch
    git clone https://github.com/fastai/fastai_pytorch
    cd fastai_pytorch
    pip install -e .

`cupy` at the moment is only required for QRNNs, so chances are you don't need it.

**Comment by stas00** [comment]
Alternative pip way - just tested:

    pip install torch_nightly -f https://download.pytorch.org/whl/nightly/cu92/torch_nightly.html
    pip install --index-url https://test.pypi.org/simple/ --extra-index-url  https://pypi.org/simple/ fastai==1.0.0b2

**Comment by sgugger** [comment]
Cupy has been removed by [this commit](https://github.com/fastai/fastai_pytorch/commit/a3232b46018412369ca10e182fed00bfc3a48829) as it's not necessary for almost all the features and the plan is to not depend on it at the end.
This should solve the issue.

**Comment by VathsalaAchar** [comment]
Perfect, installation was straightforward this time. Thank you all for your help!
