### ISSUE TITLE
conda install -c pytorch pytorch-nightly suggests cpu version

### ISSUE THREAD

**Issue by shang-vikas** [fastai/fastai_pytorch#48]
hey,
I tried  `conda install -c pytorch pytorch-nightly` and it suggested cpu version for installation.
Is this correct behaviour and one needs to explicitly install the gpu version or is something wrong??

**Comment by stas00** [comment]
Please review the options under https://pytorch.org/get-started/locally/, you need the cuda package for the gpu, e.g. with CUDA 9.2 it's:

    conda install pytorch torchvision cuda92 -c pytorch

For no cuda, it suggests an explicit:

    conda install pytorch-cpu torchvision-cpu -c pytorch

though I haven't tried it. As most likely it'll install torch-0.4.1 which is too old.

You're correct though that we should probably include in the install docs to look at the url above to figure out the GPU part. I have updated README.md to reflect that.

Do let us know how things work out.

**Comment by shang-vikas** [comment]
@stas00 I tried several options and figured out that 
when you run `conda install -c pytorch pytorch-nightly` , conda suggests to install the package based on the cuda version you have installed(`conda install cudaXX -c pytorch`).
* if **no cuda** is installed it suggests the **cpu** version.

Now if a cuda version is installed like cuda90 and its available in today's nightly build for your python version, then it will install the correct package, but if nightly build is **not available** for your python version, then it will fall back to the **cpu** version. The workaround is to install the previous day's nightly build for correct cuda and python version 
So i think to avoid confusion, README.md should be updated to install the explicit previous day's nightly version - something like
`conda install -c pytorch cuda92 --yes && conda install -c pytorch pytorch-nightly=1.0.0.dev2018MM(DD-1)``
what's your opinion?

**Comment by shang-vikas** [comment]
Readme updated again. It looks all good now, so no need of this, closing. Thanks

**Comment by stas00** [comment]
Your testing and feedback is very appreciated, Vikas.

It's going to be changed yet again later in the day, as we are simplifying the process.

And it'll become very simple once pytorch-1.0.0 conda packages get released.
