### ISSUE TITLE
Issue with fastai installation

### ISSUE THREAD

**Issue by DrHB** [fastai/fastai_pytorch#50]
Hey, 
I am trying to install fastai using PyPI but keep getting this issue.. 

```
  Could not find a version that satisfies the requirement torch>=0.4.9 (from fastai==1.0.0b3) (from versions: 0.1.2, 0.1.2.post1, 0.3.1, 0.4.0, 0.4.1)
No matching distribution found for torch>=0.4.9 (from fastai==1.0.0b3)
```

also if I try to go via dev installation I get same issue, 

```
  Using cached https://files.pythonhosted.org/packages/62/08/09ced1bae24016d96a1ddad0e0516275f113d929adf1fbd4a30a88002d68/fastprogress-0.1.5-py3-none-any.whl
Requirement already satisfied: ipython in /home/bukharih/anaconda3/envs/fast_v_1/lib/python3.6/site-packages (from fastai==1.0.0b3) (6.5.0)
Requirement already satisfied: matplotlib in /home/bukharih/anaconda3/envs/fast_v_1/lib/python3.6/site-packages (from fastai==1.0.0b3) (2.2.3)
Requirement already satisfied: numpy>=1.12 in /home/bukharih/anaconda3/envs/fast_v_1/lib/python3.6/site-packages (from fastai==1.0.0b3) (1.15.1)
Requirement already satisfied: pandas in /home/bukharih/anaconda3/envs/fast_v_1/lib/python3.6/site-packages (from fastai==1.0.0b3) (0.23.4)
Requirement already satisfied: Pillow in /home/bukharih/anaconda3/envs/fast_v_1/lib/python3.6/site-packages (from fastai==1.0.0b3) (5.2.0)
Requirement already satisfied: scipy in /home/bukharih/anaconda3/envs/fast_v_1/lib/python3.6/site-packages (from fastai==1.0.0b3) (1.1.0)
Collecting spacy (from fastai==1.0.0b3)
  Using cached https://files.pythonhosted.org/packages/24/de/ac14cd453c98656d6738a5669f96a4ac7f668493d5e6b78227ac933c5fd4/spacy-2.0.12.tar.gz
Collecting torch>=0.4.9 (from fastai==1.0.0b3)
  Could not find a version that satisfies the requirement torch>=0.4.9 (from fastai==1.0.0b3) (from versions: 0.1.2, 0.1.2.post1, 0.3.1, 0.4.0, 0.4.1)
No matching distribution found for torch>=0.4.9 (from fastai==1.0.0b3)
```

**Comment by stas00** [comment]
Thank you for this feedback, @DrHB. 

Are you following the instructions [here](https://github.com/fastai/fastai_pytorch/blob/master/README.md#pypi-install)

which should have installed pytorch-1.0.0 beta.

**Comment by DrHB** [comment]
Thank you very much for the fast replay, yes I followed the instructions. 
Also there is an issue with Conda... installation


```
PackageNotFoundError: Packages missing in current channels:
            
  - fastai

We have searched for the packages in the following channels:
            
  - https://conda.anaconda.org/pytorch/linux-64
  - https://conda.anaconda.org/pytorch/noarch
  - https://conda.anaconda.org/fastai/linux-64
  - https://conda.anaconda.org/fastai/noarch
  - https://repo.continuum.io/pkgs/main/linux-64
  - https://repo.continuum.io/pkgs/main/noarch
  - https://repo.continuum.io/pkgs/free/linux-64
  - https://repo.continuum.io/pkgs/free/noarch
  - https://repo.continuum.io/pkgs/r/linux-64
  - https://repo.continuum.io/pkgs/r/noarch
  - https://repo.continuum.io/pkgs/pro/linux-64
  - https://repo.continuum.io/pkgs/pro/noarch
```

**Comment by stas00** [comment]
yes, a recent change removed a part that wasn't quite ready to be removed, sorry about that.

For conda do:

    conda install -c pytorch -c fastai/label/test torchvision=0.2.1=pyhe7f20fa_0 fastai cuda92

For pypi, if you have installed:

  pip install torch_nightly -f https://download.pytorch.org/whl/nightly/cu92/torch_nightly.html

successfully, then the requirement for torch>=0.4.9 should be satisfied. No? Can you please check where things got installed?

**Comment by stas00** [comment]
Thank you for confirming that the update conda instructions work.

wrt pypi, do you get the same?
```
$ python -c "import torch; print(torch.__version__)"
1.0.0.dev20180927
```

Also when doing pip install I get:

```
$ pip install --index-url https://test.pypi.org/simple/ --extra-index-url  https://pypi.org/simple/ fastai==1.0.0b3
[...]
Requirement already satisfied: torch>=0.4.9 in /home/stas/anaconda3/envs/pytorch-dev/lib/python3.6/site-packages (from fastai==1.0.0b3) (1.0.0.dev20180927)
[...]
```

**Comment by DrHB** [comment]
ha! could this be the issue my version is 28 and you have a chance 27?

` python -c "import torch; print(torch.__version__)"`
`1.0.0.dev20180928`

**Comment by stas00** [comment]
It oddly appears to be so, or perhaps I had several versions installed, i removed all vestiges of pytorch and installed nightly 1.0.0.dev20180929 and now I am able to reproduce your problem 

```
Collecting torch>=0.4.9 (from fastai==1.0.0b3)
  Could not find a version that satisfies the requirement torch>=0.4.9 (from fastai==1.0.0b3) (from versions: 0.1.2, 0.1.2.post1, 0.3.1, 0.4.0, 0.4.1)
No matching distribution found for torch>=0.4.9 (from fastai==1.0.0b3)
```
I'm just finishing up a new conda package and then will work on this one. 

Thanks again.

**Comment by DrHB** [comment]
Awesomeee! Thank you very much!

**Comment by stas00** [comment]
OK, I found a workaround for the dependency issue for torchvision. If you could uninstall torchvision/fastai (can keep torch_nightly) and then follow the updated [instructions](https://github.com/fastai/fastai_pytorch/blob/master/README.md#pypi-install) and please let me know whether this does the trick.

This of course will all get resolved once all the 1.0.0 versions are out...

Thank you for testing, @DrHB.

**Comment by DrHB** [comment]
Awesome! Just tested it works smoooothly =)

**Comment by stas00** [comment]
Excellent. Thank you for testing, @DrHB
